//! Generating the block that tells an agent what it may do.
//!
//! An agent behaves far better when told its capabilities than when made to
//! discover them by failing. Generating the block *from the policy* — and
//! stamping it with the policy generation hash — closes the loop where the
//! documentation says one thing and the ruleset does another: `aido check` can
//! compare the stamp and fail CI when a doc has drifted.
//!
//! The text is deliberately short, imperative, and free of alternatives. It is
//! parsed by a language model, and hedging is what produces the ambiguity that
//! gets misread.

use aido_policy::rule::ConfirmPolicy;
use aido_policy::{RuleSet, Tier};

/// Which harness the block is written for.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DocFormat {
    /// `CLAUDE.md`.
    Claude,
    /// `AGENTS.md`, the cross-harness convention.
    Agents,
    /// Codex CLI.
    Codex,
}

/// The sentinel that opens a generated block.
pub const BEGIN: &str = "<!-- aido:begin v1 -->";
/// The sentinel that closes a generated block.
pub const END: &str = "<!-- aido:end -->";

/// Renders the block for `rules`.
///
/// `generation` is the ruleset's content hash, written into the block so drift
/// is detectable.
pub fn render(rules: &RuleSet, generation: &str, format: DocFormat) -> String {
    let mut out = String::new();
    out.push_str(BEGIN);
    out.push('\n');
    out.push_str("## Privileged commands\n\n");

    if rules.is_empty() {
        out.push_str(
            "No privileged action is allowed. Do not use sudo. Do not use aido.\nAsk the user to run privileged commands.\n",
        );
        push_footer(&mut out, generation, format);
        return out;
    }

    out.push_str("Do not use sudo. Use aido. It runs an approved list only.\n\n");
    out.push_str("You may run these:\n\n");

    for action in rules.actions() {
        let confirm = action.confirm == ConfirmPolicy::Always || action.tier.always_confirms();
        let mut line = format!("- `{}` — {}", action.id, describe_tier(action.tier));
        if confirm {
            line.push_str(". A human must approve it");
        }
        if !action.agent_allowed {
            line.push_str(". You may NOT run this; a human must");
        }
        line.push('\n');
        out.push_str(&line);
    }

    out.push_str(
        "\nRules:\n\
         - Run one action per call.\n\
         - Pass a real argument list. Do not pass a shell string.\n\
         - If aido denies a command, read the `remediation` field. Do it.\n\
         - Do not retry a command that was denied as `deny_listed`. It will never work.\n\
         - Do not look for another way to run a denied command.\n\
         \n\
         Check a command before you run it:\n\
         \n\
         ```\n\
         aido explain --output json -- <command> <args>\n\
         ```\n",
    );

    push_footer(&mut out, generation, format);
    out
}

fn push_footer(out: &mut String, generation: &str, format: DocFormat) {
    out.push_str("\nGenerated by `aido agentdoc --format ");
    out.push_str(match format {
        DocFormat::Claude => "claude",
        DocFormat::Agents => "agents",
        DocFormat::Codex => "codex",
    });
    out.push_str("`. Policy generation `");
    out.push_str(generation.get(..12).unwrap_or(generation));
    out.push_str("`. Do not edit by hand.\n");
    out.push_str(END);
    out.push('\n');
}

/// One short clause per tier, in the plainest words available.
fn describe_tier(tier: Tier) -> &'static str {
    match tier {
        Tier::DiagRead => "reads system state",
        Tier::SvcControl => "starts, stops, or restarts a service",
        Tier::PkgInstall => "installs a package from a configured repository",
        Tier::PkgRemove => "removes or upgrades packages",
        Tier::SysTunable => "changes a kernel or system setting",
        Tier::NetFilter => "changes the firewall",
        Tier::Critical => "is high risk",
    }
}

#[cfg(test)]
mod tests {
    #![allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
        clippy::indexing_slicing,
        clippy::arithmetic_side_effects
    )]

    use super::*;

    fn rules() -> RuleSet {
        RuleSet::from_toml(
            "10-a.toml",
            r#"
[[action]]
id = "aido.svc.restart"
tier = "svc-control"
exe = "/usr/bin/systemctl"
args = [{ name = "unit", matcher = { name = "unit-name" } }]

[[action]]
id = "aido.pkg.remove"
tier = "pkg-remove"
exe = "/usr/bin/apt-get"
confirm = "always"
args = [{ name = "pkg", matcher = { name = "deb-name" } }]

[[action]]
id = "aido.mount"
tier = "critical"
exe = "/usr/bin/mount"
agent_allowed = false
args = [{ name = "t", matcher = { literal = "/mnt" } }]
"#,
        )
        .unwrap()
    }

    #[test]
    fn the_block_is_delimited_so_it_can_be_updated_in_place() {
        let text = render(&rules(), "abcdef0123456789", DocFormat::Agents);
        assert!(text.starts_with(BEGIN));
        assert!(text.trim_end().ends_with(END));
    }

    #[test]
    fn every_action_appears_with_a_plain_language_description() {
        let text = render(&rules(), "abcdef0123456789", DocFormat::Agents);
        assert!(text.contains("`aido.svc.restart` — starts, stops, or restarts a service"));
        assert!(text.contains("`aido.pkg.remove` — removes or upgrades packages"));
    }

    #[test]
    fn an_action_needing_approval_says_so() {
        let text = render(&rules(), "gen", DocFormat::Agents);
        assert!(text.contains("aido.pkg.remove"));
        let line = text
            .lines()
            .find(|l| l.contains("aido.pkg.remove"))
            .unwrap();
        assert!(line.contains("A human must approve it"), "{line}");
    }

    #[test]
    fn a_human_only_action_tells_the_agent_not_to_try() {
        let text = render(&rules(), "gen", DocFormat::Agents);
        let line = text.lines().find(|l| l.contains("aido.mount")).unwrap();
        assert!(line.contains("You may NOT run this"), "{line}");
        // A critical tier also always confirms, so both clauses appear.
        assert!(line.contains("A human must approve it"), "{line}");
    }

    #[test]
    fn an_empty_ruleset_tells_the_agent_to_use_nothing() {
        // The correct thing to say on a fresh install: not "here is how", but
        // "there is nothing".
        let text = render(&RuleSet::default(), "gen", DocFormat::Agents);
        assert!(text.contains("No privileged action is allowed"));
        assert!(text.contains("Do not use aido"));
        assert!(text.trim_end().ends_with(END));
    }

    #[test]
    fn the_block_carries_a_truncated_generation_stamp() {
        let text = render(&rules(), "0123456789abcdefdeadbeef", DocFormat::Agents);
        assert!(text.contains("`0123456789ab`"), "{text}");
        // A short hash is not truncated into a panic.
        let short = render(&rules(), "abc", DocFormat::Agents);
        assert!(short.contains("`abc`"));
    }

    #[test]
    fn each_format_names_itself_in_the_generated_block() {
        for (format, expected) in [
            (DocFormat::Claude, "claude"),
            (DocFormat::Agents, "agents"),
            (DocFormat::Codex, "codex"),
        ] {
            let text = render(&rules(), "gen", format);
            assert!(text.contains(&format!("--format {expected}")), "{text}");
            assert!(format!("{format:?}").len() > 3);
        }
        assert_eq!(DocFormat::Agents, DocFormat::Agents);
        assert_ne!(DocFormat::Agents, DocFormat::Claude);
    }

    #[test]
    fn the_instructions_tell_the_agent_to_stop_on_a_permanent_denial() {
        // The behaviour that matters most: an agent that keeps hunting for a
        // variant after a deny_listed verdict is the failure mode to prevent.
        let text = render(&rules(), "gen", DocFormat::Agents);
        assert!(text.contains("will never work"));
        assert!(text.contains("Do not look for another way"));
    }

    #[test]
    fn every_tier_has_a_description() {
        for tier in [
            Tier::DiagRead,
            Tier::SvcControl,
            Tier::PkgInstall,
            Tier::PkgRemove,
            Tier::SysTunable,
            Tier::NetFilter,
            Tier::Critical,
        ] {
            assert!(describe_tier(tier).len() > 8, "{tier:?}");
        }
    }
}
